// <auto-generated />
namespace SmartStore.DependingPrices.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ItemGroupId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemGroupId));
        
        string IMigrationMetadata.Id
        {
            get { return "201903031349439_ItemGroupId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
