// <auto-generated />
namespace SmartStore.DependingPrices.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Indizes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Indizes));
        
        string IMigrationMetadata.Id
        {
            get { return "202104060943549_Indizes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
